### ISSUE TITLE
Gather data about a workflow run

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/multivac#10]
Gather data from each workfow run:

- timestamps: added to queue, starting on runner, finished
- runner label
- runner version
- job name
- platform: `amd64` or `aarch64`, get from workflow name

This data will be stored in a database and later used for flaky test analytics.

---

OS and version are out of scope

We have two types of jobs:

- dockerized — all package builds for Linux → out of scope of this issue
- build on runner — tests on Linux, builds on MacOS, FreeBSD, Linux at gravitons (?), fuzzing

```json
  {
    "debug": {
      "platform": "amd64",
      "OS": "Ubuntu",
      "OS_version": "20.04",
    },
    "release": {
      ...
    }
  }
```

**Comment by lastoCHka42** [comment]
@NickVolynkin I have a couple of questions:
1. What the difference between platform and OS and version?
2. Is it OK if we will get OS and version from runner label?

**Comment by Totktonada** [comment]
I can't say what exactly Nick want to collect, but I can reveal my initial ideas on the project structure and thoughts how it may evolve in a future.

There are three main parts: download, analyze, report. Let's look on them a bit deeper.

* `fetch.py` just fetches all new data. There are some simple filters to reduce time to fetch, traffic and amount of storage (say, collect only particular branches), but the key idea is just 'renew the data'.
* There are `sensors` to analyze the data. I have implemented a sensor to get test statuses from logs (it looks as the most useful one). I would also highlight that some data are already present as JSON, so they don't require sensors to extract necessary information.
* And there are `reports`. I have implemented `last_seen` report, which in fact just filters test status sensor output and presents it as a CSV/HTML file. There is also `minutes` report, which is purely based on JSON data and don't use any sensors.

Back to your questions. Let's start with fourth:

> 4. Should I gather data in `fetch.py`, in `last_seen.py` or create new file?

Definitely not in `fetch.py`, but anything else depends on the goal. Do you want to create a new report? Okay, let's add the new script to create the report and all sensors it needs (if it needs them). Do you want to saturate the `last_seen` report with more information? Let's improve it so.

Nick's issue does not answer this question. I would ask him what is the final result we should get. I would not start to write a code before we'll have at least a rough idea what is the goal.

We can look on it from a bit different angle. Let's consider the initial request:

> This data will be stored in a database and later used for flaky test analytics.

We definitely need such component as the database, because now we can't easily join results of different sensors[^1]. So I'm sure we'll end with the following four components: download, analyze, store, report.

[^1]: It is also not easy to create an arbitrary index or add a precalculated aggregate.

I would propose to start from creating a database schema for exiting data. The easiest (and, I guess, the best) way to design it is to follow the data types we already have in the domain of the problem.

* workflow_run
* workflow_run_job

I suggest to prefer [natural](https://en.wikipedia.org/wiki/Natural_key) primary keys as opposed to surrogate ones, where possible. Consider using composite natural keys, when there is no unique singleton keys.

Say, we have tables for the source data (likely just parsed JSON files from GitHub). We want to saturate this data with information from sensors. There are two kinds of sensors:

1. Saturates existing table. The example is a reason of failure of given workflow run job: test fail or other.
2. Extracts information such as a list of failed tests.

We can just add a column for the first kind of sensor. We can add a table for the second one.

I suggest to avoid premature decomposition into different tables. Simplicity of data representation often matters more than some level of extra of memory/disk usage. Let's decompose only whether a particular report needs it.

We also may need some stored aggregates. Say, a table, which counts amount of fails of a particular test.

I highly recommend to ask youself the following question about each field in the database: how exactly it will be used? It is the opposite of 'let's just store it'. I think, however, that the source data may be stored as is. But everything else should be considered in a light of a particular usage (IOW, particular report to generate).

I think that tarantool is very promising choice for the database here: lazy structurization and JSON path indexes allow to use it as an object oriented database. Ability to add more indexes to the existing data will allow to add more reports to look on the information from different angles.
